# Generated by Django 4.2.6 on 2023-10-13 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.community')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_as_mentor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_as_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
