# Generated by Django 4.2.5 on 2023-10-07 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('content', models.CharField(max_length=255)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.community')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCommunity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('is_mentor', models.BooleanField(blank=True, default=False)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.community')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestMentor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upadate_date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('UserCommunityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_in_community', to='Member.usercommunity')),
                ('mentorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesting_mentors', to='Member.usercommunity')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MetamarskID', models.CharField(max_length=255)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
