# Generated by Django 4.2.5 on 2023-10-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommunity',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
