# Generated by Django 4.2.5 on 2023-10-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_alter_usercommunity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommunity',
            name='score',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
